sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
- 7.1

dist: trusty

os: linux

git:
  depth: 1
  submodules: false

before_install:
- php -v
- php -m
- alias composer="php-n -d memory_limit=-1 $(which composer)"
- travis_retry composer self-update --stable
- travis_retry composer update --prefer-dist --no-interaction --no-suggest --no-plugins

script:
- $(which php) vendor/bin/phpunit
